# Generated by Django 6.0.7 on 2026-07-08 17:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('member_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('membership_start_date', models.DateField(blank=True, null=True)),
                ('membership_end_date', models.DateField(blank=True, null=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('photo_id_proof', models.ImageField(blank=True, null=True, upload_to='members/id_proofs/')),
                ('membership_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='plans.membershipplan')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members',
                'indexes': [models.Index(fields=['member_id', 'status'], name='members_member__238ad7_idx'), models.Index(fields=['status', 'membership_end_date'], name='members_status_8f6fc1_idx'), models.Index(fields=['full_name', 'phone_number'], name='members_full_na_cbc573_idx')],
            },
        ),
    ]
